### ISSUE TITLE
nvim-lspconfig setup is not correct

### ISSUE THREAD

**Issue by schang412** [acereca/srls#2]
Hi, thanks for writing this. 

I tried following the instructions for using this LSP with `nvim-lspconfig`. However, I couldn't get the currently documented setup to work correctly. 

Here is the setup that I found which worked:
```lua
require('lspconfig.configs').srls = {
    default_config = {
        cmd = {"/absolute/path/to/srls"},
        filetypes = {"skill"},
        root_dir = require('lspconfig.util').root_pattern(".git")
    }
}
require('lspconfig').srls.setup({})
```

The error message associated with the documented method is:
```
[lspconfig] Cannot access configuration for srls. Ensure this server is listed in `server_configurations.md` or added as a custom server.
```
It is probably because srls is not yet a supported language server by nvim-config. Let me know if you would like me to file a pull request for this.

**Comment by acereca** [comment]
seems i missed that, thanks for spotting
